language: python
python:

  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

script:

  - coverage run --omit=*.virtualenvs*,*virtualenv* python/main.py test

after_success:
  - coveralls
  - codecov

sudo: enabled
dist: trusty
